language: r
pandoc_version: 1.17.2
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
after_failure:
  - ./travis-tool.sh dump_logs
r_packages:
  - packrat
deploy:
  - provider: pages
    target_branch: netlify-plumber
    local_dir: _toolbar_book
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
before_script:
  - chmod +x ./_build.sh
script:
  - ./_build.sh
